### ISSUE TITLE
emoji.wpf makes an exception if it cannot render the emoji

### ISSUE THREAD

**Issue by disable-0001** [samhocevar/emoji.wpf#39] opened 2021-04-08 10:41 UTC
Example of line: `<Image Height="24" emoji:Image.Source="🧱"/>`

I got a user of my software that doesn't have support for these types of emojis cuz he is running Windows 8, making the program generate an exception and it won't load the emojis.

Is there any way we can handle this exception? I'm loading the emoji via XAML.

Thanks!

**Comment by samhocevar** [comment] 2021-04-08 14:43
Do you think you could find the exception message, stack trace etc.? I’ll try to investigate the problem but the exception details would be really helpful.

**Comment by SicknessDev** [comment] 2021-04-10 14:44
`Het instellen van eigenschap Emoji.Wpf.Image.Source heeft een uitzondering veroorzaakt. regelnummer 435 en regelpositie 36.
   bij System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   bij System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   bij System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   bij System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   bij Restocks.MainWindow.InitializeComponent()
   bij Restocks.MainWindow..ctor()
PresentationFramework
`

Sorry, the user is from Denmark, couldn't get it in English

**Comment by SicknessDev** [comment] 2021-04-16 10:40
> La propriété Set 'Emoji.Wpf.Image.Source' a levé une exception.
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   à -.I1iIil1Il1II.InitializeComponent()
   à -.I1iIil1Il1II..ctor()
PresentationFramework

Other one over here, thanks!

**Comment by disable-0001** [comment] 2021-07-11 19:35
Any news into this ? I need to build two releases, one without this library due to it crashes loading the emojis visually.

**Comment by samhocevar** [comment] 2021-07-21 09:21
Hi! I tried to reproduce the problem and found a crash on Windows 8 that was fixed in Emoji.Wpf version 0.3.3. Could you maybe confirm this was the same problem?

**Comment by samhocevar** [comment] 2022-11-17 08:08
I’m closing this issue because I believe it was fixed. Please feel free to reopen if the problem is still there.

**Closed by samhocevar** 2022-11-17 08:08 UTC
Labels: bug
