### ISSUE TITLE
TextBlock support?

### ISSUE THREAD

**Issue by cybercatgurrl** [samhocevar/emoji.wpf#1] opened 2018-04-15 10:07 UTC
I'd do it myself but I'm not sure I comprehend what your code is doing.

**Comment by samhocevar** [comment] 2018-04-16 12:59
It’s still very rough, I am not sure of what the exact architecture should be.

In commit f284cee962559ac25f23072309110b47e4627140 I have rewritten `emoji:Image` so that it behaves more like a `TextBlock` and I have renamed it `emoji:TextBlock`. Please let me know whether that works for you!

![image](https://user-images.githubusercontent.com/245089/38810303-af51be98-4186-11e8-8695-cf1d78838ec4.png)

**Comment by cybercatgurrl** [comment] 2018-04-20 17:42
Aside from missing a couple properties which was easy to fix, I need Inlines support so that I can bind values with Run. Without Run I was able to get the text to show up by assigning the property to TextBlock but that's not what I want to do.

**Comment by samhocevar** [comment] 2018-04-23 09:34
I see. Note that `m_textblock` is just some kind of fallback and is only used when `Text` cannot be rendered with the emoji font, so `m_textblock.Inlines` is basically useless…

I may have made a design mistake here and perhaps I should create some kind of `emoji:Run` class, too, that can be embedded in a `TextBlock`.

**Comment by samhocevar** [comment] 2018-05-13 21:14
I have started refactoring `emoji:TextBlock` so that it inherits `TextBlock` in commit 892dd5bee3d80604647f375b003034c70dcc8fe6. This will probably allow me to answer your request. Can you maybe clarify what it is you do with `Inlines`?

**Comment by Kumar2Harsh** [comment] 2018-08-23 05:00
i am getting "Could not load file or assembly 'Emoji.Wpf, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified." error on " <wpf:TextBlock></wpf:TextBlock>" line how to solve it

**Comment by samhocevar** [comment] 2018-11-05 10:50
Sorry for the lack of answer, but I do not know how to fix or even reproduce the above problem… did you eventually find a way?

**Comment by samhocevar** [comment] 2021-03-16 15:12
Hi everyone. I’m choosing to close this bug because I think the original issue was fixed a long time ago, and other problems, if still relevant, should have their own issue.

**Closed by samhocevar** 2021-03-16 15:12 UTC
